"""empty message

Revision ID: 04c280a81acc
Revises: cf574b931d6b
Create Date: 2024-07-10 10:37:31.205135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c280a81acc'
down_revision: Union[str, None] = 'cf574b931d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EventInfo',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], name=op.f('fk_EventInfo_admin_id_user')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_EventInfo'))
    )
    with op.batch_alter_table('TimeTable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('fk_TimeTable_admin_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_TimeTable_event_id_EventInfo'), 'EventInfo', ['event_id'], ['event_id'])
        batch_op.drop_column('users')
        batch_op.drop_column('region')
        batch_op.drop_column('event_name')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TimeTable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('event_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('region', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('users', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_TimeTable_event_id_EventInfo'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['admin_id'], ['id'])
        batch_op.drop_column('event_id')
        batch_op.drop_column('id')

    op.drop_table('EventInfo')
    # ### end Alembic commands ###
