"""Add event_type column and Middle Table

Revision ID: 38875abe589e
Revises: 04c280a81acc
Create Date: 2024-07-10 20:13:28.339626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38875abe589e'
down_revision: Union[str, None] = '04c280a81acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TimeTable_backup')
    with op.batch_alter_table('EventInfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_type', sa.String(), nullable=False))
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('event_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('region',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('TimeTable', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('event_time',
               existing_type=sa.NUMERIC(),
               type_=sa.DateTime(),
               nullable=False)

    with op.batch_alter_table('event_user_association', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user_timetable_association', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('timetable_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_timetable_association', schema=None) as batch_op:
        batch_op.alter_column('timetable_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('event_user_association', schema=None) as batch_op:
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('TimeTable', schema=None) as batch_op:
        batch_op.alter_column('event_time',
               existing_type=sa.DateTime(),
               type_=sa.NUMERIC(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('EventInfo', schema=None) as batch_op:
        batch_op.alter_column('region',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('event_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('event_type')

    op.create_table('TimeTable_backup',
    sa.Column('event_time', sa.NUMERIC(), nullable=True),
    sa.Column('users', sa.TEXT(), nullable=True),
    sa.Column('admin_id', sa.INTEGER(), nullable=True)
    )
    # ### end Alembic commands ###
