"""empty message

Revision ID: cf574b931d6b
Revises: 99b3307c4300
Create Date: 2024-07-04 10:33:33.290566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf574b931d6b'
down_revision: Union[str, None] = '99b3307c4300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TimeTable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_TimeTable_admin_id_user'), 'user', ['admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TimeTable', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_TimeTable_admin_id_user'), type_='foreignkey')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
